ENEMY_SHIP_DATA = {
    "bug_3": {
        "speed": 100,
        "hp": 25,
        "sprite_sheet": "bug_3",
        "primary_weapons": [["standard", (32, 0)]],
        "secondary_weapons": [],
        "secondary_offsets": [(20, 16), (44, 16)],
        "projectile_color": "Red",
        "movement_behavior": "forward_behavior",
        "fire_behavior": "random_single_fire_behavior",
        "fire_behavior_args": [500],
        "shield_args": [],
    },
    "bug_3_dt": {
        "speed": 100,
        "hp": 25,
        "sprite_sheet": "bug_3",
        "primary_weapons": [["standard", (32, 0)]],
        "secondary_weapons": [],
        "secondary_offsets": [(20, 16), (44, 16)],
        "projectile_color": "Red",
        "movement_behavior": "s_behavior",
        "fire_behavior": "random_double_tap_fire_behavior",
        "fire_behavior_args": [750],
        "shield_args": [],
    },
    "bug_3_b": {
        "speed": 100,
        "hp": 25,
        "sprite_sheet": "bug_3",
        "primary_weapons": [["standard", (32, 0)]],
        "secondary_weapons": ["side_cannon"],
        "secondary_offsets": [(20, 16), (44, 16)],
        "projectile_color": "Red",
        "movement_behavior": "stall_behavior",
        "fire_behavior": "random_burst_fire_behavior",
        "fire_behavior_args": [1000, 4],
        "shield_args": [25, 0.5, 2000],
    },
}
