ENEMY_SHIP_DATA = {
    "bug_1": {
        "speed": 75,
        "hp": 30,
        "sprite_sheet": "bug_1",
        "primary_weapons": [],
        "secondary_weapons": ["side_cannon", "side_cannon"],
        "secondary_offsets": [[(24, 16), (40, 16)], [(20, 16), (44, 16)]],
        "projectile_color": "Red",
        "movement_behavior": "forward_behavior",
        "fire_behavior": "single_fire_behavior",
        "fire_behavior_args": [1500],
        "shield_args": [],
    },
    "bug_2": {
        "speed": 200,
        "hp": 20,
        "sprite_sheet": "bug_2",
        "primary_weapons": [["standard", (32, 0)]],
        "secondary_weapons": [],
        "secondary_offsets": [],
        "projectile_color": "Red",
        "movement_behavior": "s_behavior",
        "fire_behavior": "double_tap_fire_behavior",
        "fire_behavior_args": [750],
        "shield_args": [],
    },
    "bug_3": {
        "speed": 75,
        "hp": 50,
        "sprite_sheet": "bug_3",
        "primary_weapons": [["turbolaser", (32, 0)]],
        "secondary_weapons": ["missile"],
        "secondary_offsets": [[(20, 16), (44, 16)]],
        "projectile_color": "Red",
        "movement_behavior": "stall_behavior",
        "fire_behavior": "single_fire_behavior",
        "fire_behavior_args": [1000],
        "shield_args": [25, 0.5, 2000],
    },
    "bug_4": {
        "speed": 100,
        "hp": 25,
        "sprite_sheet": "bug_4",
        "primary_weapons": [["sniper", (20, 16)], ["sniper", (44, 16)]],
        "secondary_weapons": [],
        "secondary_offsets": [],
        "projectile_color": "Red",
        "movement_behavior": "zig_zag_behavior",
        "fire_behavior": "single_fire_behavior",
        "fire_behavior_args": [1500],
        "shield_args": [25, 0.5, 2000],
    },
    "bug_5": {
        "speed": 125,
        "hp": 50,
        "sprite_sheet": "bug_5",
        "primary_weapons": [["beam", (32, 0)]],
        "secondary_weapons": [],
        "secondary_offsets": [],
        "projectile_color": "Red",
        "movement_behavior": "zig_zag_behavior",
        "fire_behavior": "beam_fire_behavior",
        "fire_behavior_args": [1500, 250],
        "shield_args": [],
    },
    "bug_6": {
        "speed": 75,
        "hp": 75,
        "sprite_sheet": "bug_6",
        "primary_weapons": [["turbolaser", (20, 16)], ["turbolaser", (44, 16)]],
        "secondary_weapons": [],
        "secondary_offsets": [],
        "projectile_color": "Red",
        "movement_behavior": "circle_behavior",
        "fire_behavior": "single_fire_behavior",
        "fire_behavior_args": [1500],
        "shield_args": [50, 0.25, 2000],
    },
}
