ENEMY_SHIP_DATA = {
    "bug_1": {
        "multipliers": {
            "speed": 0.75,
            "hp": 0.3,
            "shield_strength": 0.25,
            "shield_cooldown": 1,
            "shield_regen": 1,
        },
        "sprite_sheet": "bug_1",
        "primary_weapons": [],
        "secondary_weapons": ["side_cannon", "side_cannon"],
        "secondary_offsets": [[(24, 16), (40, 16)], [(20, 16), (44, 16)]],
        "projectile_color": "Red",
        "movement_behavior": "forward_behavior",
        "fire_behavior": "single_fire_behavior",
        "fire_behavior_args": [1500],
        "start_with_shield": False,
    },
    "bug_2": {
        "multipliers": {
            "speed": 1.5,
            "hp": 0.2,
            "shield_strength": 0.25,
            "shield_cooldown": 0.5,
            "shield_regen": 1,
        },
        "sprite_sheet": "bug_2",
        "primary_weapons": [["standard", (32, 0)]],
        "secondary_weapons": [],
        "secondary_offsets": [],
        "projectile_color": "Red",
        "movement_behavior": "s_behavior",
        "fire_behavior": "double_tap_fire_behavior",
        "fire_behavior_args": [750],
        "start_with_shield": False,
    },
    "bug_3": {
        "multipliers": {
            "speed": 0.75,
            "hp": 0.5,
            "shield_strength": 0.5,
            "shield_cooldown": 1,
            "shield_regen": 1,
        },
        "speed": 75,
        "hp": 50,
        "sprite_sheet": "bug_3",
        "primary_weapons": [["turbolaser", (32, 0)]],
        "secondary_weapons": ["missile"],
        "secondary_offsets": [[(20, 16), (44, 16)]],
        "projectile_color": "Red",
        "movement_behavior": "stall_behavior",
        "fire_behavior": "single_fire_behavior",
        "fire_behavior_args": [1000],
        "start_with_shield": False,
    },
    "bug_4": {
        "multipliers": {
            "speed": 1,
            "hp": 0.25,
            "shield_strength": 0.25,
            "shield_cooldown": 1,
            "shield_regen": 1,
        },
        "sprite_sheet": "bug_4",
        "primary_weapons": [["sniper", (20, 16)], ["sniper", (44, 16)]],
        "secondary_weapons": [],
        "secondary_offsets": [],
        "projectile_color": "Red",
        "movement_behavior": "zig_zag_behavior",
        "fire_behavior": "single_fire_behavior",
        "fire_behavior_args": [1500],
        "start_with_shield": False,
    },
    "bug_5": {
        "multipliers": {
            "speed": 1.25,
            "hp": 0.5,
            "shield_strength": 0.25,
            "shield_cooldown": 2,
            "shield_regen": 1,
        },
        "sprite_sheet": "bug_5",
        "primary_weapons": [["beam", (32, 0)]],
        "secondary_weapons": [],
        "secondary_offsets": [],
        "projectile_color": "Red",
        "movement_behavior": "zig_zag_behavior",
        "fire_behavior": "beam_fire_behavior",
        "fire_behavior_args": [1500, 250],
        "start_with_shield": False,
    },
    "bug_6": {
        "multipliers": {
            "speed": 0.75,
            "hp": 0.75,
            "shield_strength": 0.5,
            "shield_cooldown": 1,
            "shield_regen": 1,
        },
        "sprite_sheet": "bug_6",
        "primary_weapons": [["turbolaser", (20, 16)], ["turbolaser", (44, 16)]],
        "secondary_weapons": [],
        "secondary_offsets": [],
        "projectile_color": "Red",
        "movement_behavior": "circle_behavior",
        "fire_behavior": "single_fire_behavior",
        "fire_behavior_args": [1500],
        "start_with_shield": False,
    },
}
