PLAYER_SHIP_DATA = {
    "Stalker": {
        "speed": 400,
        "hp": 100,
        "sprite_sheet": "planes_01A",
        "primary_weapons": [["standard", (48, 20)]],
        "secondary_weapons": ["side_cannon"],
        "secondary_offsets": [[(40, 35), (56, 35)]],
        "projectile_color": "Green",
        "shield_args": [100, 1, 1000],
    },
    "Viper": {
        "speed": 600,
        "hp": 75,
        "sprite_sheet": "planes_02A",
        "primary_weapons": [["sniper", (48, 20)]],
        "secondary_weapons": ["side_cannon"],
        "secondary_offsets": [[(40, 35), (56, 35)]],
        "projectile_color": "Green",
        "shield_args": [50, 1, 500],
    },
    "Pheonix": {
        "speed": 400,
        "hp": 75,
        "sprite_sheet": "planes_03A",
        "primary_weapons": [["gatling", (48, 20)]],
        "secondary_weapons": ["side_cannon"],
        "secondary_offsets": [[(40, 35), (56, 35)]],
        "projectile_color": "Blue",
        "shield_args": [75, 1, 500],
    },
    "Defiance": {
        "speed": 350,
        "hp": 100,
        "sprite_sheet": "planes_04A",
        "primary_weapons": [["standard", (48, 20)]],
        "secondary_weapons": ["side_cannon", "missile"],
        "secondary_offsets": [[(40, 35), (56, 35)], [(30, 40), (66, 40)]],
        "projectile_color": "Blue",
        "shield_args": [75, 1, 1000],
    },
    "Valiant": {
        "speed": 500,
        "hp": 75,
        "sprite_sheet": "planes_05A",
        "primary_weapons": [["beam", (48, 20)]],
        "secondary_weapons": ["side_cannon"],
        "secondary_offsets": [[(40, 35), (56, 35)]],
        "projectile_color": "Green",
        "shield_args": [75, 1, 1000],
    },
    "Corsair": {
        "speed": 500,
        "hp": 100,
        "sprite_sheet": "planes_07A",
        "primary_weapons": [["gatling", (44, 20)], ["gatling", (52, 20)]],
        "secondary_weapons": [],
        "secondary_offsets": [],
        "projectile_color": "Blue",
        "shield_args": [100, 1, 1500],
    },
    "Leopard": {
        "speed": 300,
        "hp": 150,
        "sprite_sheet": "planes_08A",
        "primary_weapons": [["turbolaser", (48, 20)]],
        "secondary_weapons": ["side_cannon"],
        "secondary_offsets": [[(36, 25), (60, 25)]],
        "projectile_color": "Green",
        "shield_args": [150, 1, 1000],
    },
    "Lightning": {
        "speed": 300,
        "hp": 125,
        "sprite_sheet": "planes_09A",
        "primary_weapons": [],
        "secondary_weapons": ["side_cannon", "side_cannon", "side_cannon"],
        "secondary_offsets": [
            [(40, 35), (56, 35)],
            [(34, 40), (62, 40)],
            [(28, 40), (68, 40)],
        ],
        "projectile_color": "Blue",
        "shield_args": [125, 1, 1000],
    },
    "Test": {
        "speed": 500,
        "hp": 200,
        "sprite_sheet": "planes_03A",
        "primary_weapons": [["turbolaser", (48, 20)]],
        "secondary_weapons": ["torpedo"],
        "secondary_offsets": [
            [(40, 35), (56, 35)],
            [(34, 40), (62, 40)],
            [(28, 40), (68, 40)],
        ],
        "projectile_color": "Blue",
        "shield_args": [125, 1, 1000],
    },
}
