PLAYER_SHIP_DATA = {
    "Stalker": {
        "multipliers": {
            "speed": 4,
            "hp": 1.25,
            "shield_strength": 1,
            "shield_cooldown": 1,
            "shield_regen": 1,
        },
        "sprite_sheet": "planes_01A",
        "primary_weapons": [["standard", (48, 20)]],
        "secondary_weapons": [],
        "secondary_offsets": [[(40, 35), (56, 35)], [(30, 40), (66, 40)]],
        "projectile_color": "Green",
        "start_with_shield": False,
    },
    "Viper": {
        "multipliers": {
            "speed": 6,
            "hp": 0.75,
            "shield_strength": 0.5,
            "shield_cooldown": 0.75,
            "shield_regen": 1.25,
        },
        "sprite_sheet": "planes_02A",
        "primary_weapons": [["sniper", (48, 20)]],
        "secondary_weapons": [],
        "secondary_offsets": [[(40, 35), (56, 35)], [(30, 40), (66, 40)]],
        "projectile_color": "Green",
        "start_with_shield": False,
    },
    "Pheonix": {
        "multipliers": {
            "speed": 4,
            "hp": 0.9,
            "shield_strength": 0.75,
            "shield_cooldown": 0.75,
            "shield_regen": 1.5,
        },
        "sprite_sheet": "planes_03A",
        "primary_weapons": [["gatling", (48, 20)]],
        "secondary_weapons": [],
        "secondary_offsets": [[(40, 35), (56, 35)], [(30, 40), (66, 40)]],
        "projectile_color": "Blue",
        "start_with_shield": False,
    },
    "Defiance": {
        "multipliers": {
            "speed": 3.5,
            "hp": 1,
            "shield_strength": 1.25,
            "shield_cooldown": 1.25,
            "shield_regen": 1.25,
        },
        "sprite_sheet": "planes_04A",
        "primary_weapons": [["standard", (48, 20)]],
        "secondary_weapons": [],
        "secondary_offsets": [[(40, 35), (56, 35)], [(30, 40), (66, 40)]],
        "projectile_color": "Blue",
        "start_with_shield": False,
    },
    "Valiant": {
        "multipliers": {
            "speed": 5,
            "hp": 0.75,
            "shield_strength": 0.75,
            "shield_cooldown": 1,
            "shield_regen": 0.75,
        },
        "sprite_sheet": "planes_05A",
        "primary_weapons": [["beam", (48, 20)]],
        "secondary_weapons": ["side_cannon"],
        "secondary_offsets": [
            [(40, 35), (56, 35)],
            [(30, 40), (66, 40)],
            [(28, 40), (68, 40)],
        ],
        "projectile_color": "Green",
        "start_with_shield": True,
    },
    "Corsair": {
        "multipliers": {
            "speed": 5,
            "hp": 1,
            "shield_strength": 1,
            "shield_cooldown": 1,
            "shield_regen": 0.75,
        },
        "sprite_sheet": "planes_07A",
        "primary_weapons": [["gatling", (44, 20)], ["gatling", (52, 20)]],
        "secondary_weapons": [],
        "secondary_offsets": [[(36, 25), (60, 25)]],
        "projectile_color": "Blue",
        "start_with_shield": False,
    },
    "Leopard": {
        "multipliers": {
            "speed": 3,
            "hp": 1.5,
            "shield_strength": 1.5,
            "shield_cooldown": 1,
            "shield_regen": 1.5,
        },
        "sprite_sheet": "planes_08A",
        "primary_weapons": [["turbolaser", (48, 20)]],
        "secondary_weapons": [],
        "secondary_offsets": [[(36, 25), (60, 25)], [(34, 40), (62, 40)]],
        "projectile_color": "Green",
        "start_with_shield": False,
    },
    "Lightning": {
        "multipliers": {
            "speed": 3,
            "hp": 1.25,
            "shield_strength": 1.25,
            "shield_cooldown": 1,
            "shield_regen": 1.25,
        },
        "sprite_sheet": "planes_09A",
        "primary_weapons": [],
        "secondary_weapons": ["side_cannon", "side_cannon"],
        "secondary_offsets": [
            [(40, 35), (56, 35)],
            [(34, 40), (62, 40)],
            [(28, 40), (68, 40)],
            [(22, 42), (74, 42)],
        ],
        "projectile_color": "Blue",
        "start_with_shield": False,
    },
    "Test": {
        "multipliers": {
            "speed": 5,
            "hp": 1,
            "shield_strength": 1,
            "shield_cooldown": 1,
            "shield_regen": 1,
        },
        "speed": 500,
        "hp": 200,
        "sprite_sheet": "planes_03A",
        "primary_weapons": [["gatling", (48, 20)]],
        "secondary_weapons": ["missile"],
        "secondary_offsets": [
            [(40, 35), (56, 35)],
            [(34, 40), (62, 40)],
            [(28, 40), (68, 40)],
        ],
        "projectile_color": "Blue",
        "start_with_shield": True,
    },
}
