# Game window settings
HEIGHT = 1000
WIDTH = 800
FPS = 60

# Animation settings
FRAME_TIME = 100

# Missile default settings
MISSILE_SPEED = 600
MISSILE_BORESIGHT = 45
MISSILE_TURN_RATE = 1.5
MISSILE_VISION = 500
MISSILE_COOLDOWN = 5
PRO_NAV_CONST = 5
