main:
	g++ -std=c++17 -I"C:\SFML-2.5.1\include" -o project3.exe src/*.cpp *.dll -L"C:\SFML-2.5.1\lib" -lsfml-window-s -lsfml-graphics-s -lsfml-system-s -lopengl32 -lopenal32 -lfreetype -lwinmm -lgdi32 -lflac -lvorbisenc -lvorbisfile -lvorbis -logg -lws2_32 

clean:
	del project3.exe