FROM node:alpine
COPY . /app
WORKDIR /app
CMD node app.js

# docker image ls     Show local docker images
# docker system prune -a        delete all locker docker images
# docker build -t hello_docker .        build docker image
