name = input('Hello. What is your name? ')
age = input(f'It\'s nice to meet you, {name}. How old are you? ')
print(f'I see that you are still quite young at only {age}.')
location = input('Where do you live? ')
print(f'Wow! I\'ve always wanted to go to {location}. Thanks for chatting with me. Bye!')