main:
	g++ -std=c++11 -o project2.out src/project2.cpp src/Image.cpp src/Pixel.cpp src/Header.cpp

test:
	g++ -std=c++11 -o tests.exe src/tests.cpp src/Image.cpp src/Pixel.cpp src/Header.cpp

clean:
	del project2.out
	del tests.exe